# **Numpy Library**

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4]) #array format 
b = np.array([5,6,7,8]) 
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [5]:
type(a)

numpy.ndarray

### Basic Operations of Array

In [6]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


 ### Dimensions
 - 0D - np.array(2a)
 - 1D - np.array([29,30])
 - array of multiple 0D array
 - 2D - np.array([[1,2],[2,3]])
 - 3D - np.array([[[1,2],[2,3]]
 -              [[3,4][5,6]]])



In [8]:
#creating a 2D array(2Dimensions)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating a 3D array(3Dimension)
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
print(arr.shape) #shape of the array.

(2, 3)


In [8]:
print(arr.ndim) #dimension of the array.

2


In [9]:
print(arr.dtype)   #to find data type

int64


In [10]:
np.arange(11)   #to print range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [13]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [14]:
np.random.randint(10,30, size = (3,3))

array([[15, 24, 28],
       [13, 28, 22],
       [19, 21, 14]], dtype=int32)

In [16]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [23]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  0]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [17]:
print(x@y) #matrix multiplication


[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [20]:
x.prod() #product of all elements in the array

np.int64(12600)

In [21]:
x.mean() #mean of all elements in the array

np.float64(3.3333333333333335)

In [22]:
y.mean()

np.float64(3.7777777777777777)

In [24]:
round(y.mean())

4

In [25]:
x.mean(axis=0)  #mean of each column

array([4., 4., 2.])

In [26]:
y.mean(axis=1) #mean of each row

array([4.        , 4.        , 3.33333333])

In [27]:
print(x.sum())
print(x.var()) #variance
print(x.std()) #standard

30
3.3333333333333335
1.8257418583505538


In [29]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50)) #median (means 50%)
print(np.percentile(a,25)) #1st quartile (means 25%)
print(np.percentile(a,75)) #3rd quartile (means 75%)

5.0
3.0
7.0


In [30]:
b = np.random.randint(11,100, (4,4))
print(b)

[[31 46 26 20]
 [17 71 19 16]
 [30 35 69 63]
 [72 40 37 65]]


In [32]:
print("2x8")
print(b.reshape(2,8))

2x8
[[31 46 26 20 17 71 19 16]
 [30 35 69 63 72 40 37 65]]


In [33]:
print("8x2")
print(b.reshape(8,2))

8x2
[[31 46]
 [26 20]
 [17 71]
 [19 16]
 [30 35]
 [69 63]
 [72 40]
 [37 65]]


In [34]:
print(b.reshape(4,4))

[[31 46 26 20]
 [17 71 19 16]
 [30 35 69 63]
 [72 40 37 65]]


### Indexing and Slicing

In [36]:
print(b[0]) #first row
print(b[0,2]) #first row, third column
print(b[-1]) # last row
print(b[1:3]) #second and third row (slicing)
print(b[3:]) #last row

[31 46 26 20]
26
[72 40 37 65]
[[17 71 19 16]
 [30 35 69 63]]
[[72 40 37 65]]
