## Numpy Library

In [27]:
import numpy as np

In [28]:
a = np.array([1,2,3,4])    #array format 
b = np.array([5,6,7,8]) 
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [29]:
type(a)

numpy.ndarray

### Basic Operations of Array

In [30]:
print(a+b)
print(a-b)
print(a*b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


In [31]:
#creating a 2D array(2Dimensions)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [32]:
#creating a 3D array(3Dimension)
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
print(arr.shape) #shape of the array.

(2, 3)


In [34]:
print(arr.ndim) #dimension of the array.

2


In [35]:
print(arr.dtype)   #to find data type

int64


In [37]:
np.arange(11)   #to print range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [40]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])